<center>
<b><font size=6>Industry 4.0 의 중심, AI - ML&DL</font></b>
</center>

<div align='right'><font size=2 color='gray'>Machine Learning & Deep Learning with TensorFlow @ <font color='blue'><a href='https://www.facebook.com/jskim.kr'>FB / jskim.kr</a></font>, 김진수</font></div>
<hr>

# Tensor Manipulation
> 참조 : https://www.tensorflow.org/api_guides/python/array_ops

In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis

In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [7]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [8]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [9]:
(matrix1*matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

## Watch out broadcasting

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations 

In [12]:
tf.random_normal([3]).eval()

array([ 1.21104705,  0.53978473, -0.41038424], dtype=float32)

In [13]:
tf.random_uniform([2]).eval()

array([ 0.77554226,  0.9517144 ], dtype=float32)

In [14]:
tf.random_uniform([2, 3]).eval()

array([[ 0.21917546,  0.21820867,  0.22875011],
       [ 0.88537264,  0.01493788,  0.22606587]], dtype=float32)

## Reduce Mean/Sum

In [15]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [16]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [17]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [18]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [19]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [20]:
tf.reduce_sum(x).eval()

10.0

In [21]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [22]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [23]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [24]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [25]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [26]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

In [27]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [28]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [30]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [31]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

## One hot

In [32]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [33]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## casting

In [34]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [35]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [36]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [38]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip


In [40]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [41]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [42]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)2`

SyntaxError: invalid syntax (<ipython-input-42-f3b1a12e8d6f>, line 3)

In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

In [ ]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

In [ ]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

In [ ]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

<hr>
<marquee><font size=3 color='brown'>The BigpyCraft find the information to design valuable society with Technology & Craft.</font></marquee>
<div align='right'><font size=2 color='gray'> &lt; The End &gt; </font></div>