# Industry 4.0 의 중심, AI - ML&DL

<div align='right'><font size=2 color='gray'>Machine Learning & Deep Learning with TensorFlow @ <font color='blue'><a href='https://www.facebook.com/jskim.kr'>FB / jskim.kr</a></font>, 김진수</font></div>
<hr>

# Sect8. Tensor Manipulation

In [1]:
from images import bigpycraft_ai as bpc
from IPython.display import Image 
from tqdm import tqdm_notebook

In [2]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

C:\Python\Anaconda3-50\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<hr>
``` python
Init signature: pprint.PrettyPrinter(indent=1, width=80, depth=None, stream=None, *, compact=False)
Docstring:      <no docstring>
Init docstring:
Handle pretty printing operations onto a stream using a set of configured parameters.

indent  : Number of spaces to indent for each level of nesting.
width   : Attempted maximum number of columns in the output.
depth   : The maximum depth to print out nested structures.
stream  : The desired output stream.  If omitted (or false), the standard
           output stream available at construction will be used.
compact : If true, several items will be combined in one line.

```

<hr>
```python
Init signature: tf.InteractiveSession(target='', graph=None, config=None)
Docstring:     
A TensorFlow `Session` for use in interactive contexts, such as a shell.

For example:
---------------------------------------------------------------------------
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()
---------------------------------------------------------------------------
30.0

```

## <font color='brown'> Simple Array </font>

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)

array([0., 1., 2., 3., 4., 5., 6.])


In [4]:
t

array([0., 1., 2., 3., 4., 5., 6.])

In [5]:
t.ndim

1

In [6]:
t.shape

(7,)

In [7]:
t[0], t[1], t[-1]

(0.0, 1.0, 6.0)

In [8]:
t[2:5], t[4:-1]

(array([2., 3., 4.]), array([4., 5.]))

In [9]:
t[:2], t[3:]

(array([0., 1.]), array([3., 4., 5., 6.]))

## <font color='brown'> 2D Array </font>

In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [11]:
t.ndim

2

In [12]:
t.shape

(4, 3)

## <font color='brown'> Shape, Rank, Axis</font>

In [13]:
t = tf.constant([1,2,3,4])

In [14]:
tf.shape(t)

<tf.Tensor 'Shape:0' shape=(1,) dtype=int32>

In [15]:
tf.shape(t).eval()

array([4])

In [16]:
t.shape

TensorShape([Dimension(4)])

In [17]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [18]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [19]:
t.eval()

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [20]:
[
    [
        [
            [1, 2, 3, 4], 
            [5, 6, 7, 8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## <font color='brown'> Matmul VS multiply </font>

``` python 
matrix1 = [ [3, 3] ]
matrix2 = [ [2],
            [2] ]
```

In [21]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

In [22]:
matrix1.shape

TensorShape([Dimension(1), Dimension(2)])

In [23]:
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

#### <font color='blue'> matmul : M(1, 2) • M(2, 1) = M(1, 1)

In [24]:
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

#### <font color='blue'> multiply : M(1, 2) x M(2, 1) = M(2, 2)

In [25]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## <font color='brown'> Watch out broadcasting </font>

#### <font color='blue'> M(1, 2) + M(2, 1) = M(2, 2)

In [26]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [27]:
matrix1.shape

TensorShape([Dimension(1), Dimension(2)])

In [28]:
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

#### <font color='blue'> M(1, 2) + M(1, 2) = M(1, 2)

In [29]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [30]:
matrix1.shape

TensorShape([Dimension(1), Dimension(2)])

In [31]:
matrix2.shape

TensorShape([Dimension(1), Dimension(2)])

## <font color='brown'> Random values for variable initializations  </font>

### <font color='blue'> tf.random_normal
> tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
- Outputs random values from a normal distribution.
- A tensor of the specified shape filled with random normal values.

In [39]:
tf.random_normal([3]).eval()

array([-1.1352259, -1.6051586,  0.8898894], dtype=float32)

In [46]:
tf.random_normal([3], mean=5, stddev=2.5).eval()

array([6.6074257, 3.0854878, 7.459494 ], dtype=float32)

### <font color='blue'> tf.random_uniform
> tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
- Outputs random values from a uniform distribution.
- A tensor of the specified shape filled with random uniform values.
- The generated values follow a uniform distribution in the range `[minval, maxval)`.
<br> For floats, the default range is `[0, 1)`.  For ints, at least `maxval` must be specified explicitly.

In [51]:
tf.random_uniform([2]).eval()

array([0.23258352, 0.5240853 ], dtype=float32)

In [52]:
tf.random_uniform([2, 3]).eval()

array([[0.8195708 , 0.08741391, 0.9691185 ],
       [0.03592694, 0.3762555 , 0.3009007 ]], dtype=float32)

In [56]:
tf.random_uniform([2, 3], minval=-10, maxval=10, dtype=tf.int32).eval()

array([[ 6,  8,  0],
       [ 0, -5, -1]])

## <font color='brown'> Reduce Mean/Sum  </font>

In [75]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [60]:
x = [[1., 2.],
     [3., 4.]]

In [61]:
tf.reduce_mean(x).eval()

2.5

In [62]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [41]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [63]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [64]:
tf.reduce_sum(x).eval()

10.0

In [65]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [66]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [67]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## <font color='brown'> Argmax with axis </font>

### <font color='blue'> tf.argmax
> Returns the index with the largest value across axes of a tensor.
- Returns : A `Tensor` of type `int64`.

In [76]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [77]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [78]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## <font color='brown'> Reshape, squeeze, expand_dims </font>

### <font color='blue'> tf.reshape
> Reshapes a tensor.
- If one component of `shape` is the special value -1, the size of that dimension
is computed so that the total size remains constant.  <br>In particular, a `shape`
of `[-1]` flattens into 1-D.  At most one component of `shape` can be -1. 
<br><br>
- If `shape` is 1-D or higher, then the operation returns a tensor with shape
`shape` filled with the values of `tensor`. <br>In this case, the number of elements
implied by `shape` must be the same as the number of elements in `tensor`.

In [79]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [80]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [81]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### <font color='blue'> tf.squeeze
> tf.squeeze(input, axis=None, name=None, squeeze_dims=None)
- Removes dimensions of size 1 from the shape of a tensor.

In [82]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

### <font color='blue'> tf.expand_dims
> tf.expand_dims(input, axis=None, name=None, dim=None)
- Inserts a dimension of 1 into a tensor's shape.

In [83]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

In [86]:
tf.expand_dims([0, 1, 2], 0).eval()

array([[0, 1, 2]])

## <font color='brown'> One hot </font>

### <font color='blue'> tf.expand_dims
> tf.one_hot(indices, depth, on_value=None, off_value=None, axis=None, dtype=None, name=None)
- Returns a one-hot tensor.
- indices: A `Tensor` of indices.
- depth: A scalar defining the depth of the one hot dimension.
- on_value: A scalar defining the value to fill in output when `indices[j] = i`. (default: 1)
- off_value: A scalar defining the value to fill in output when `indices[j] != i`. (default: 0)
- axis: The axis to fill (default: -1, a new inner-most axis).
- dtype: The data type of the output tensor.


In [92]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [93]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## <font color='brown'> Casting </font>

### <font color='blue'> tf.cast
> tf.cast(x, dtype, name=None)
- Casts a tensor to a new type.
- x: A `Tensor` or `SparseTensor`.
- dtype: The destination type.
- name: A name for the operation (optional).

In [94]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [95]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## <font color='brown'> Stack </font>

### <font color='blue'> tf.stack
> tf.stack(values, axis=0, name='stack')
- Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor.
- Packs the list of tensors in `values` into a tensor with rank one higher than 
each tensor in `values`, by packing them along the `axis` dimension.
Given a list of length `N` of tensors of shape `(A, B, C)`;
<br> - if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
<br> - if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.

In [59]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [60]:
# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## <font color='brown'> Ones like and Zeros like </font>

In [62]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [63]:
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [64]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## <font color='brown'> Zip </font>

In [65]:
for something in zip([1, 2, 3], [4, 5, 6]):
    print(something)

(1, 4)
(2, 5)
(3, 6)


In [66]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [67]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## <font color='brown'> Transpose </font>

### <font color='blue'> tf.transpose
> tf.transpose(a, perm=None, name='transpose')
- Transposes `a`. Permutes the dimensions according to `perm`.
- a: A `Tensor`.
- perm: A permutation of the dimensions of `a`.
- name: A name for the operation (optional).

In [68]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [69]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [70]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [71]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [72]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


<hr>
<marquee><font size=3 color='brown'>The BigpyCraft find the information to design valuable society with Technology & Craft.</font></marquee>
<div align='right'><font size=2 color='gray'> &lt; The End &gt; </font></div>